### ISSUE TITLE
Acessar uma nota que não existe derruba a aplicação

### ISSUE THREAD

**Issue by pedosb** [pedosb/note#14]
Se tentar acessar uma nota que não existe (`/notes/nao_existe`) a aplicação morre, acho que a melhor estratégia seria retornar 404

**Comment by itelo** [comment]
isso nao seria outra issue?

2015-04-28 17:39 GMT-03:00 Pedro Batista notifications@github.com:

**Comment by pedosb** [comment]
Mas é outra issue ué, o bug que comentei no pull request é outro...

**Comment by itelo** [comment]
Aah, foi mal, apareceu para mim como se fosse um comentario.
