### ISSUE TITLE
Erro "ioerror: [errno 2] no such file or directory: '.notes'"

### ISSUE THREAD

**Issue by brunoricardojava** [pedosb/note#5]
Pessoal, fui testar o código trabalhado na nossa ultima reunião e sem fazer nem uma alteração acabou ocorrendo o seguinte erro: "**ioerror: [errno 2] no such file or directory: '.notes'**". Acredito que tenha a ver com essa função:

``` python
def load(self):
      bkp = open(self.bkp_file, 'r')
      self.note_dic = json.loads(bkp.read())
```

Se alguém, já tiver solucionado esse problema coloque a solução.  Vlw...

**Comment by pedosb** [comment]
Legal, o problema é que assumimos que o arquivos que tem as notas (".notes" por default) sempre existe. Para resolver acho que seria legal usar exceções, bastaria fazer um try...catch por IOError e se a exceção acontecer basta inicializar o self.note_dic como um dicionário vazio.

https://docs.python.org/2/tutorial/errors.html

**Comment by brunoricardojava** [comment]
Por que quando fizemos o test em sala não deu esse mesmo erro?

**Comment by pedosb** [comment]
Porque antes de rodar o código que lê o ".notes" rodamos o código que o criou.

**Comment by brunoricardojava** [comment]
AAAA agora lembrei.... kkkkkk Obrigado Pedro.
